# Custom Language File for Launcher Customizer

[ejs.app]
title = "PRISMA Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@PrismaStudioo"
mediaDiscordURL = "https://discord.gg/HqDWTG4tuQ"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO PRISMA Launcher"
welcomeDescription = "Sawadee kub"
welcomeDescCTA = "Hello"
